# Copyright Contributors to ETSI OSM
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

include:
  - project: 'devops/cicd'
    file: '/templates/osm-base.yml'

# Due to requirements.txt having pycurl, we need to have libcurl present
# in the scanning container so it can properly analyse it.
gemnasium-python-dependency_scanning:
  before_script:
    - apt-get update -y
    - DEBIAN_FRONTEND=noninteractive apt-get -y install libcurl4-openssl-dev
