FROM alpine:3.17.1

RUN apk update
RUN apk add --no-cache python3 py3-pip
RUN pip install --upgrade pip

COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENV PORT 5000

EXPOSE 5000

CMD [ "python", "openid.py" ]