FROM alpine:3.17.1

RUN apk update
RUN apk add --no-cache python3 py3-pip

RUN pip install --upgrade pip

WORKDIR /app
COPY . /app
ENV PATH="$PATH:/app/.local/bin"
RUN pip install -r requirements.txt

# Expomos a porta
EXPOSE 5001
# Colocamos o servidor a correr
CMD [ "python", "auth_server.py" ]